version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mongodb:/data

  keycloak:
    container_name: admin
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8443:8080
    command:
      - start-dev
