server:
  port: ${PORT:8080}

config:
  private-key: chave-super-secreta-2

keycloak:
  enabled: true
  realm: caixinha-auth-server
  host: https://lemur-5.cloud-iam.com/auth
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

bot-builder:
  read-timeout: 30000
  base-url: https://bot-builder-engine-2242d70bd3b3.herokuapp.com

logging:
  level:
      springframework:
        security: DEBUG
        web:
          client: DEBUG

mongodb:
  principal:
    uri: ${MONGO_URL:mongodb://localhost:27017/flow}
  admin:
    uri: ${MONGO_URL:mongodb://localhost:27017/flow}

spring:
  data:
    mongodb:
      uri: ${mongodb.principal.uri}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
