server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: react-app
            client-secret: 2arXto0aypTRw4AqcSJsnfRR1JQFQKCk
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bot-flow
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bot-flow