server:
  port: ${PORT:8080}

keycloak:
  enabled: true

bot-builder:
  read-timeout: 30000
  base-url: https://bot-builder-engine-2242d70bd3b3.herokuapp.com

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/flow}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: react-app
            client-secret: 2arXto0aypTRw4AqcSJsnfRR1JQFQKCk
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8443/realms/bot-flow
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/bot-flow